# Generated by Django 4.0.2 on 2022-02-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_events_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected_message',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Content'),
        ),
    ]
